name: ride_fare_app
description: "A new Flutter project."
dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  sliding_up_panel: ^2.0.0+1
  geolocator: ^10.1.0
  http: ^0.13.3
  provider: ^6.1.1
  flutter_localizations:
    sdk: flutter
environment:
  sdk: ">=2.17.0 <4.0.0"
flutter:
  uses-material-design: true
